<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="pskindero-ThinkPad-Edge-E545" ignored="0" name="Default test" tests="9" failures="2" timestamp="22 May 2017 19:19:11 GMT" time="3.129" errors="0">
  <testcase name="restGET_AllDepartments_Parse" time="2.35" classname="com.pskindero.javaee.javaeetech.endpoints.DepartmentsRestTest"/>
  <testcase name="restGET_AllDepartments_ResultOk" time="0.064" classname="com.pskindero.javaee.javaeetech.endpoints.DepartmentsRestTest"/>
  <testcase name="restGET_DupaDepartment_ResultOk" time="0.056" classname="com.pskindero.javaee.javaeetech.endpoints.DepartmentsRestTest"/>
  <testcase name="restGET_AllEmployees_Parse" time="0.17" classname="com.pskindero.javaee.javaeetech.endpoints.EmployeesRestTest">
    <failure type="javax.ws.rs.ProcessingException" message="org.codehaus.jackson.map.exc.UnrecognizedPropertyException: Unrecognized field &amp;quot;department&amp;quot; (Class com.pskindero.javaee.javaeetech.jpa.entity.Employee), not marked as ignorable
 at [Source: org.apache.http.conn.EofSensorInputStream@24ba9639; line: 1, column: 128] (through reference chain: com.pskindero.javaee.javaeetech.jpa.entity.Employee[&amp;quot;department&amp;quot;])">
      <![CDATA[javax.ws.rs.ProcessingException: org.codehaus.jackson.map.exc.UnrecognizedPropertyException: Unrecognized field "department" (Class com.pskindero.javaee.javaeetech.jpa.entity.Employee), not marked as ignorable
 at [Source: org.apache.http.conn.EofSensorInputStream@24ba9639; line: 1, column: 128] (through reference chain: com.pskindero.javaee.javaeetech.jpa.entity.Employee["department"])
	at org.jboss.resteasy.client.jaxrs.internal.ClientResponse.readFrom(ClientResponse.java:282)
	at org.jboss.resteasy.client.jaxrs.internal.ClientResponse.readEntity(ClientResponse.java:178)
	at org.jboss.resteasy.specimpl.BuiltResponse.readEntity(BuiltResponse.java:226)
	at com.pskindero.javaee.javaeetech.endpoints.EmployeesRestTest.restGET_AllEmployees_Parse(EmployeesRestTest.java:26)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
Caused by: org.codehaus.jackson.map.exc.UnrecognizedPropertyException: Unrecognized field "department" (Class com.pskindero.javaee.javaeetech.jpa.entity.Employee), not marked as ignorable
 at [Source: org.apache.http.conn.EofSensorInputStream@24ba9639; line: 1, column: 128] (through reference chain: com.pskindero.javaee.javaeetech.jpa.entity.Employee["department"])
	at org.codehaus.jackson.map.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:53)
	at org.codehaus.jackson.map.deser.StdDeserializationContext.unknownFieldException(StdDeserializationContext.java:267)
	at org.codehaus.jackson.map.deser.std.StdDeserializer.reportUnknownProperty(StdDeserializer.java:673)
	at org.codehaus.jackson.map.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:659)
	at org.codehaus.jackson.map.deser.BeanDeserializer.handleUnknownProperty(BeanDeserializer.java:1365)
	at org.codehaus.jackson.map.deser.BeanDeserializer._handleUnknown(BeanDeserializer.java:725)
	at org.codehaus.jackson.map.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:703)
	at org.codehaus.jackson.map.deser.BeanDeserializer.deserialize(BeanDeserializer.java:580)
	at org.codehaus.jackson.map.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:217)
	at org.codehaus.jackson.map.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:194)
	at org.codehaus.jackson.map.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:30)
	at org.codehaus.jackson.map.ObjectMapper._readValue(ObjectMapper.java:2704)
	at org.codehaus.jackson.map.ObjectMapper.readValue(ObjectMapper.java:1315)
	at org.codehaus.jackson.jaxrs.JacksonJsonProvider.readFrom(JacksonJsonProvider.java:419)
	at org.jboss.resteasy.core.interception.jaxrs.AbstractReaderInterceptorContext.readFrom(AbstractReaderInterceptorContext.java:66)
	at org.jboss.resteasy.core.interception.jaxrs.AbstractReaderInterceptorContext.proceed(AbstractReaderInterceptorContext.java:56)
	at org.jboss.resteasy.client.jaxrs.internal.ClientResponse.readFrom(ClientResponse.java:248)
	... 28 more
]]>
    </failure>
  </testcase> <!-- restGET_AllEmployees_Parse -->
  <testcase name="restGET_AllEmployees_ResultOk" time="0.052" classname="com.pskindero.javaee.javaeetech.endpoints.EmployeesRestTest"/>
  <testcase name="restGET_FirstEmployee_ResultOk" time="0.054" classname="com.pskindero.javaee.javaeetech.endpoints.EmployeesRestTest"/>
  <testcase name="restGET_AllManagers_Parse" time="0.144" classname="com.pskindero.javaee.javaeetech.endpoints.ManagersRestTest"/>
  <testcase name="restGET_AllManagers_ResultOk" time="0.055" classname="com.pskindero.javaee.javaeetech.endpoints.ManagersRestTest"/>
  <testcase name="restGET_FirstManager_ResultOk" time="0.047" classname="com.pskindero.javaee.javaeetech.endpoints.ManagersRestTest">
    <failure type="java.lang.AssertionError" message="Invalid response status expected [200] but found [204]">
      <![CDATA[java.lang.AssertionError: Invalid response status expected [200] but found [204]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:388)
	at com.pskindero.javaee.javaeetech.util.BaseRestTest.execGetAndAssertIfNotOkStatus(BaseRestTest.java:22)
	at com.pskindero.javaee.javaeetech.endpoints.ManagersRestTest.restGET_FirstManager_ResultOk(ManagersRestTest.java:33)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
    </failure>
  </testcase> <!-- restGET_FirstManager_ResultOk -->
</testsuite> <!-- Default test -->
